hibernate:

spring:
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
server:
  port: 8080
